### ISSUE TITLE
WIRE Failed Install on Ubuntu Mate 17.04 (Feb2017 MATE Distro Build)

### ISSUE THREAD

**Issue by ml48603** [atom/node-nslog#23]
I attempted to install WIRE on Ubuntu Mate 17.04 unsuccessfully.  I followed the instructions posted at https://github.com/wireapp/wire-desktop

The following errors were generated:

$ sudo npm install

> nslog@3.0.0 install /home/mark/wire-desktop/node_modules/nslog
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.10.0-8-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/mark/wire-desktop/node_modules/nslog
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
wire-desktop@ /home/mark/wire-desktop
├── abbrev@1.0.9 
├── aproba@1.0.4 
├── asap@2.0.5 
├── config-chain@1.1.11 
├─┬ electron-builder@12.3.1
│ ├── minimatch@3.0.3 
│ └── semver@5.3.0 
├─┬ electron-packager@8.5.2
│ └─┬ asar@0.13.0
│   └── glob@6.0.4 
├─┬ electron-winstaller@2.5.2
│ └─┬ asar@0.11.0
│   └── glob@6.0.4 
├─┬ eslint@3.17.0
│ ├─┬ concat-stream@1.5.0
│ │ └── inherits@2.0.3 
│ ├─┬ glob@7.1.1
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2 
│ │ └── once@1.4.0 
│ └── path-is-inside@1.0.2 
├── fstream@1.0.10 
├─┬ fstream-npm@1.2.0 
│ └─┬ fstream-ignore@1.0.5
│   └── minimatch@3.0.3 
├─┬ glob@7.1.0 
│ └── minimatch@3.0.3 
├── graceful-fs@4.1.9 
├── has-unicode@2.0.1 
├── inherits@2.0.3 
├── lockfile@1.0.2 
├── lodash.clonedeep@4.5.0 
├── lodash.union@4.6.0 
├── lodash.uniq@4.5.0 
├── lodash.without@4.4.0 
├── minimatch@3.0.3 
├─┬ node-gyp@3.4.0 
│ └── minimatch@3.0.3 
├── npm-package-arg@4.2.0 
├─┬ npm-registry-client@7.2.1 
│ └── retry@0.10.0 
├── npm-user-validate@0.1.5 
├── npmlog@4.0.0 
├── once@1.4.0 
├── opener@1.4.2 
├── path-is-inside@1.0.2 
├─┬ read-package-tree@5.1.5 
│ └─┬ read-package-json@2.0.4
│   └── glob@6.0.4 
├── readable-stream@2.1.5 
├── request@2.75.0 
├── retry@0.10.0 
├── rimraf@2.5.4 
├── semver@5.3.0 
├── sorted-object@2.0.1 
├── which@1.2.11 
├── wrappy@1.0.2 
└── write-file-atomic@1.2.0 

npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-mac:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-mac@1.0.1
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.2
npm ERR! Linux 4.10.0-8-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mark/wire-desktop/npm-debug.log

npm-debug.log was not created in installation directory

Please let me know what has to be done to build wire on Ubuntu Mate 17.04.

Thanks,
Mark

**Comment by 50Wliu** [comment]
Looks like it can't find node.  What does `which node` return?

**Comment by ml48603** [comment]
$ which node

Returns nothing. what is node ?

**Comment by 50Wliu** [comment]
Node is what is used to run this module (and also Wire).  It's built on Chrome's V8 engine.  That's not really important though if all you want is to install Wire.  Install Node from https://nodejs.org/en/ and after installation try installing Wire again.

**Comment by ml48603** [comment]
Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model

What kind of security holes is this package opening up in the OS ?
