### ISSUE TITLE
Win: nslog fails to install globally

### ISSUE THREAD

**Issue by justinmchase** [atom/node-nslog#7]
```
$ iojs --version
v2.3.0
```

This fails for me on windows:
`npm install nslog -g`

However if I install it non-globally it works fine. Consequently, i cannot install `electron-rebuild` globally because nslog fails to compile. The error says it cannot find `win_delay_load_hook.c`, which does exist on my system just not in places where its looking, which seems broken.

```
Warning: Missing input files:
c:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\Program Files\iojs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
  win_delay_load_hook.c
c1 : fatal error C1083: Cannot open source file: 'c:Program Files\iojs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c': No such file or directory [C:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\nslog.vcxpr oj]
```

The first path:
`c:\Users\justin\AppData\Roaming\npm\node_modules\nslog\build\Program Files\iojs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c`

is just completely wrong.

The second path:
`c:Program Files\iojs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c`

Just appears to be broken around `c:Program Files` which should probably be `c:\Program Files`. The file is actually at that path.

**Comment by wojohowitz** [comment]
This has been sitting a while... I can't find any resources other than this... 
here's me:
\node\tryble\node_modules\electron-rebuild\node_modules\nslog\src\nslog.h(4): fatal error C1083: Cannot open include file: 'string': No such file or directory (..\src\main.cc) [\node_modules\electron-rebuild\node_modules\nslog\build\nslog.vcxproj]
\tryble\node_modules\electron-rebuild\node_modules\nslog\src\nslog.h(4): fatal error C1083: Cannot open include file: 'string': No such file or directory (..\src\nslog_win.cc) [\node\tryble\node_modules\electron-rebuild\node_modules\nslog\build\nslog.vcxproj]

I'm at my wits end here.
