### ISSUE TITLE
hard-coded dependency

### ISSUE THREAD

**Issue by bortch** [atom/node-nslog#9]
Hello,

I'm trying to install electron-rebuild which has nslog as dependency and I get:
     ```fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz```
 
My proxies setting are OK (it works with others repo).

How about to replace:
```javascript
    "dependencies": {
        "nan": "https://atom.io/download/atom-shell/nan-1.6.1.tgz"
      }
```
by
```javascript
    "dependencies": {
        "nan": "1.6.1"
      }
```
?

Settings:
win32 x64
node v0.12.7
npm  v2.11.3

**Comment by ssreekanth** [comment]
nslog 3.0.0 fixes this issue. It can be closed now.
